// message-bus.js

const MSG_TYPES = {
  GET_DETECTED_MEDIA: 'GET_DETECTED_MEDIA',
  VIDGRAB_FOUND_MEDIA: 'VIDGRAB_FOUND_MEDIA',
  VIDGRAB_URL: 'VIDGRAB_URL',
  VIDGRAB_SEGMENT: 'VIDGRAB_SEGMENT',
  VIDGRAB_FORWARD_SEGMENT: 'VIDGRAB_FORWARD_SEGMENT',
  START_DOWNLOAD_TIER1: 'START_DOWNLOAD_TIER1',
  DOWNLOAD_PROGRESS: 'DOWNLOAD_PROGRESS',
  DOWNLOAD_COMPLETE: 'DOWNLOAD_COMPLETE',
  DOWNLOAD_ERROR: 'DOWNLOAD_ERROR',
  VIDGRAB_START_TIER3: 'VIDGRAB_START_TIER3',
  DOWNLOAD_PROGRESS_TIER3: 'DOWNLOAD_PROGRESS_TIER3',
  DOWNLOAD_COMPLETE_TIER3: 'DOWNLOAD_COMPLETE_TIER3',
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MSG_TYPES };
}
